repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.3

  gir: org.realityforge.gir:gir-core:jar:0.11

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  graphql_java: com.graphql-java:graphql-java:jar:13.0

  slf4j_api: org.slf4j:slf4j-api:jar:1.7.25
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.7.25
  antlr4_runtime: org.antlr:antlr4-runtime:jar:4.7.2

  javapoet: com.squareup:javapoet:jar:1.12.0

  yasson: org.eclipse:yasson:jar:1.0.4
  jakarta_json: org.glassfish:jakarta.json:jar:1.1.5
  jakarta_json_api: jakarta.json:jakarta.json-api:jar:1.1.5
  jakarta_json_bind: jakarta.json.bind:jakarta.json.bind-api:jar:1.0.1

  javaee_api: javax:javaee-api:jar:8.0

  keycloak_jaxrs_client_authfilter: org.realityforge.keycloak.client.authfilter:keycloak-jaxrs-client-authfilter:jar:1.02
