repositories:
  remote:
   - https://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.13

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0

  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.2

  gir: org.realityforge.gir:gir-core:jar:0.09

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.98

  graphql_java: com.graphql-java:graphql-java:jar:12.0

  slf4j_api: org.slf4j:slf4j-api:jar:1.7.25
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.7.25
  antlr4_runtime: org.antlr:antlr4-runtime:jar:4.7.2

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.10
  guava: com.google.guava:guava:jar:25.0-jre
